module.exports = [
    {
        id: "4780c8ef-6659-4f56-a6ea-cd0486a39f59",
        first_name: "Simon",
        last_name: "Harlow",
        avatar_url: "https://dgalywyr863hv.cloudfront.net/pictures/athletes/7159950/5912114/5/large.jpg",
        city: "Squamish",
        state: "BC",
        country: "Canada",
        strava_id: 7159950,
        strava_url: "https://www.strava.com/athletes/7159950",
        fav_activity_1: "Running",
        fav_activity_2: "Downhill Skiing",
        fav_activity_3: "Hiking",
        bio: "Feel free to join me on a run in Squamish or a ski at Whistler!"
    },
    {
        id: "f12afe76-8d17-460a-9311-1bd594446db2",
        first_name: "Rebecca",
        last_name: "Harper",
        avatar_url: "https://dgalywyr863hv.cloudfront.net/pictures/athletes/17753466/12730740/3/large.jpg",
        city: "Squamish",
        state: "BC",
        country: "Canada",
        strava_id: 17753466,
        strava_url: "https://www.strava.com/athletes/17753466",
        fav_activity_1: "Running",
        fav_activity_2: "Downhill Skiing",
        fav_activity_3: "Cycling",
        bio: "I like anything in the mountains, so lets go!!!"
    },
    {
        id: "2418c1d1-3c94-4ca1-a48b-6661612e8c06",
        first_name: "Lisa",
        last_name: "Danielson",
        avatar_url: "https://dgalywyr863hv.cloudfront.net/pictures/athletes/27060692/7867720/3/large.jpg",
        city: "Vancouver",
        state: "BC",
        country: "Canada",
        strava_id: 27060692,
        strava_url: "https://www.strava.com/athletes/27060692",
        fav_activity_1: "Running",
        fav_activity_2: "Nordic Skiing",
        fav_activity_3: "Cycling",
        bio: "Living in East Vancouver but always up for a Nordic on Cypress, hit me up if you wanna join"
    },
    {
        id: "0ee12bff-6b36-4656-9260-66b4d89f336a",
        first_name: "Rob",
        last_name: "Samuel",
        avatar_url: "https://dgalywyr863hv.cloudfront.net/pictures/athletes/947399/7494965/1/large.jpg",
        city: "Llanberis",
        state: "Wales",
        country: "United Kingdom",
        strava_id: 947399,
        strava_url: "https://www.strava.com/athletes/947399",
        fav_activity_1: "Running",
        fav_activity_2: "Hiking",
        fav_activity_3: "Cycling",
        bio: "Former Salomon sponsored athlete who lives running and cycling, join me if you can keep up!"
    },
    {
        id: "a28128b6-451a-4fa0-bf88-4a85348f3915",
        first_name: "Jeff",
        last_name: "Pelletier",
        avatar_url: "https://dgalywyr863hv.cloudfront.net/pictures/athletes/2513942/787277/2/large.jpg",
        city: "Vancouver",
        state: "BC",
        country: "Canada",
        strava_id: 2513942,
        strava_url: "https://www.strava.com/athletes/2513942",
        fav_activity_1: "Running",
        fav_activity_2: "Downhill Skiing",
        fav_activity_3: "Hiking",
        bio: "North Van YouTuber who loves meeting people and filimng as I go along, check out my channel!"
    },
    {
        id: "fbdfa9be-a28a-4011-a66a-0b8551da9f9f",
        first_name: "Dave",
        last_name: "Hughes",
        avatar_url: "https://dgalywyr863hv.cloudfront.net/pictures/athletes/1131439/6509927/3/large.jpg",
        city: "Stockport",
        state: "England",
        country: "United Kingdom",
        strava_id: 1131439,
        strava_url: "https://www.strava.com/athletes/1131439",
        fav_activity_1: "Running",
        fav_activity_2: "Hiking",
        fav_activity_3: "Cycling",
        bio: "Casual road and trail runner, join me so I'm not on my own!"
    },
    {
        id: "e12fb7d6-c3f9-497e-b649-391fc079d93a",
        first_name: "Jim",
        last_name: "Walmsley",
        avatar_url: "https://dgalywyr863hv.cloudfront.net/pictures/athletes/1635688/650395/5/large.jpg",
        city: "Chamonix",
        state: "Rhone-Alps",
        country: "France",
        strava_id: 1635688,
        strava_url: "https://www.strava.com/pros/1635688",
        fav_activity_1: "Running",
        fav_activity_2: "Nordic Skiing",
        fav_activity_3: "Cycling",
        bio: "Current #1 Trail Rnner in the world, supported by Hoka. Runnng and trying to Nordic in the Alps. Dream of winning UTMB!"
    }
]